version: "3.2"

services:
  postgres:
    image: postgres:12
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: windows_app
      POSTGRES_USER: me
      POSTGRES_PASSWORD: hackme
      TZ: 'GMT+3'
      PGTZ: 'GMT+3'